name: "Create Golioth Release"
description: "Create a release in the Golioth Cloud."
branding:
  icon: "cpu"
  color: "green"

inputs:
  releaseArtifact:
    description: "Artifact to use for release."
    required: true
  releaseArtifactVersion:
    description: "Artifact version to use for release."
    required: true
  deviceTag:
    description: "Device tag used to restrict a release."
    required: false

runs:
  using: "composite"
  steps:
    - run: goliothctl dfu release create --components ${{ inputs.releaseArtifact }}@${{ inputs.releaseArtifactVersion }} --tags ${{ inputs.deviceTag }}
      shell: bash